### ISSUE TITLE
Add custom dir other than windows , linux, mac default directories

### ISSUE THREAD

**Issue by naddanki87** [cjstehno/gradle-natives#16]
Hi 
I want to add a sigar jar which depends  on natives libraries with repestive linux and windows i.e .dll and .so files which are packed in one jar named as  **sigar-1.6.4-native.jar**  and this jar is located in WEb-INF /lib/navtiveLib folder.

Or

How to add native jars from specific location to native library
e.g
compile fileTree(dir: 'web/WebContent/WEB-INF/lib', include: '*XXX--native.jar')

So how to include in native path.

**Comment by cjstehno** [comment]
I am not sure this plugin is what you are looking for... in your case it sounds like you just need the dlls and such to be picked up on your web servers library path. This plugin is meant for including native libraries in your project that are provided by its dependencies.

If I am not understanding the issue please add more details and I can reopen this.
