### ISSUE TITLE
Does this plugin work in Gradle 5?

### ISSUE THREAD

**Issue by cjstehno** [cjstehno/gradle-natives#25]
Gradle 5 brought some big changes... does this plugin still work?

**Comment by steffen-wilke** [comment]
We're using it for the [litiengine](https://github.com/gurkenlabs/litiengine) with Gradle `5.3.1` and it seems to work just fine.
I've also updated the Gradle wrapper to `6.0.1` and it's still working for us.

**Comment by cjstehno** [comment]
Good to know it's hanging in there! Thanks for verifying.
